export interface IProduct {
  id: number
  title: string
  categoryId: number
  userId: number
  description: string
  count: number
  priceTypeId: number
  availability: number
  screen: string
  image1: string
  image2: string
  image3: string
  image4: string
  image5: string
  image6: string
  image7: string
  image8: string
  image9: string
  image10: string
  videoYoutubeUrl: string
  parentId?: number
  url: string
  createdAt: Date
  updatedAt: Date
  view: number
  priceId: number
  price: number
  priceCurrency: string
  priceType: string
  categoryName: string
  sectionName: string
  countInFavorites?: 6,
  parentProduct?: IProduct
}
